Repository CherryNetwork/Cherry-Node, pull requests merged in 2022-09, with the labels that each got.

#125 increase era duration
  bin/node/runtime/src/constants.rs
Labels: A0-pleasereview, C9-critical ‼️, D1-audited 👍, B7-runtimenoteworthy, P2-asap, I6-refactor 🧹, Q2-easy

#128 revert: epoch duration
  bin/node/runtime/src/constants.rs
Labels: A0-pleasereview, B0-silent, C9-critical ‼️, D1-audited 👍, P2-asap, I6-refactor 🧹, Q2-easy

#131 fix: change spec for cherry-mainnet
  bin/node/cli/src/chain_spec.rs
Labels: A0-pleasereview, C9-critical ‼️, D1-audited 👍, B7-runtimenoteworthy, P2-asap, I6-refactor 🧹, Q9-epic

#132 Testnet chain spec
  bin/node/cli/src/chain_spec.rs
  customSpecRaw_testnet.json
Labels: A0-pleasereview, C9-critical ‼️, D1-audited 👍, B7-runtimenoteworthy, Q3-medium, P2-asap, I6-refactor 🧹

#133 Fix bonding duration
  bin/node/runtime/src/constants.rs
  bin/node/runtime/src/impls.rs
  bin/node/runtime/src/lib.rs
Labels: A0-pleasereview, C9-critical ‼️, D1-audited 👍, B7-runtimenoteworthy, Q3-medium, P2-asap, I6-refactor 🧹
