Repository CherryNetwork/Cherry-Node, pull requests merged in 2022-08, with the labels that each got.

#118 Submit payment results
  bin/node/pallets/pallet-ipfs/src/lib.rs
Labels: A0-pleasereview, D1-audited 👍, B3-apinoteworthy, C7-high ❗️, I8-enhancement 🎁, P5-sometimesoon, Q2-easy

#122 fix: storage types and multiaddr conversion
  bin/node/pallets/pallet-ipfs/src/functions.rs
  bin/node/pallets/pallet-ipfs/src/lib.rs
Labels: A0-pleasereview, D1-audited 👍, B3-apinoteworthy, I2-bug 🐜, P2-asap, C7-high ❗️, Q2-easy

#124 fix: #123 refactor `ExportIpfsStats` to contain a `Vec<IpfsNode>`
  bin/node/pallets/pallet-ipfs/src/functions.rs
  bin/node/pallets/pallet-ipfs/src/lib.rs
Labels: C9-critical ‼️, D1-audited 👍, B3-apinoteworthy, Q3-medium, P2-asap, I6-refactor 🧹, A3-inprogress

#116 Ipfs node info
  bin/node/pallets/pallet-ipfs/rpc/src/lib.rs
  bin/node/pallets/pallet-ipfs/src/functions.rs
  bin/node/pallets/pallet-ipfs/src/lib.rs
  bin/node/pallets/pallet-ipfs/src/mock.rs
  bin/node/runtime/src/constants.rs
  bin/node/runtime/src/lib.rs
Labels: A0-pleasereview, D1-audited 👍, B3-apinoteworthy, P2-asap, C7-high ❗️, I8-enhancement 🎁, Q7-involved

#113 wip: Fix global tests
  bin/node/cli/src/service.rs
  bin/node/executor/tests/basic.rs
  bin/node/executor/tests/fees.rs
  bin/node/pallets/pallet-council/src/tests.rs
  bin/node/runtime/src/impls.rs
  bin/node/runtime/src/lib.rs
  client/offchain/src/api.rs
  client/offchain/src/api/ipfs.rs
  client/offchain/src/lib.rs
  client/service/src/task_manager/tests.rs
  frame/bounties/src/tests.rs
  frame/support/test/tests/pallet.rs
  frame/tips/src/tests.rs
  primitives/core/src/offchain/testing.rs
  primitives/runtime/src/offchain/ipfs.rs
Labels: documentation, B0-silent, D1-audited 👍, I6-refactor 🧹, A3-inprogress, C1-low 📌, I4-tests 🎯
