Repository CherryNetwork/Cherry-Node, pull requests merged in 2022-06, with the labels that each got.

#98 Release
  .github/workflows/build-push-dev.yaml
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  bin/node/cli/src/chain_spec.rs
  bin/node/pallets/pallet-council/Cargo.toml
  bin/node/pallets/pallet-council/src/benchmarking.rs
  bin/node/pallets/pallet-council/src/lib.rs
  bin/node/pallets/pallet-council/src/mock.rs
  bin/node/pallets/pallet-council/src/tests.rs
  bin/node/pallets/pallet-council/src/weights.rs
  bin/node/pallets/pallet-updater/Cargo.toml
  bin/node/pallets/pallet-updater/src/benchmarking.rs
  bin/node/pallets/pallet-updater/src/lib.rs
  bin/node/pallets/pallet-updater/src/mock.rs
  bin/node/pallets/pallet-updater/src/tests.rs
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  bin/node/testing/src/genesis.rs
  docker/Dockerfile.dev
  frame/collective/src/tests.rs
  frame/system/src/lib.rs
  frame/treasury/src/lib.rs
  frame/treasury/src/tests.rs
Labels: A0-pleasereview, C9-critical ‼️, D1-audited 👍, B7-runtimenoteworthy, B3-apinoteworthy, I2-bug 🐜, P2-asap, I6-refactor 🧹, I8-enhancement 🎁, Q9-epic, I4-tests 🎯

#101 fix: technical committee memberships
  bin/node/cli/src/chain_spec.rs
  bin/node/runtime/src/lib.rs
Labels: A0-pleasereview, C9-critical ‼️, D1-audited 👍, B7-runtimenoteworthy, I2-bug 🐜, P2-asap, Q7-involved

#103 add: initial supply to treasury
  frame/treasury/src/lib.rs
Labels: A0-pleasereview, C9-critical ‼️, D1-audited 👍, B3-apinoteworthy, P2-asap, I8-enhancement 🎁, Q9-epic

#102 Mainnet chain command
  bin/node/cli/src/chain_spec.rs
  bin/node/cli/src/command.rs
  customSpecRaw_mainnet.json
Labels: A0-pleasereview, C9-critical ‼️, D1-audited 👍, B7-runtimenoteworthy, P2-asap, I8-enhancement 🎁, Q9-epic

#104 Mainnet
  Cargo.lock
  bin/node/cli/src/chain_spec.rs
  bin/node/cli/src/command.rs
  bin/node/rpc/Cargo.toml
  bin/node/rpc/src/lib.rs
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  bin/node/testing/src/genesis.rs
  customSpecRaw_mainnet.json
  frame/treasury/src/lib.rs
Labels: A0-pleasereview, C9-critical ‼️, D1-audited 👍, B7-runtimenoteworthy, B3-apinoteworthy, I2-bug 🐜, P2-asap, I8-enhancement 🎁, Q9-epic

#105 change: chain-spec changes
  customSpecRaw_mainnet.json
Labels: A0-pleasereview, B0-silent, C9-critical ‼️, D1-audited 👍, P2-asap, I6-refactor 🧹, Q9-epic

#109 add(cicd): push to ECR
  .github/workflows/build-push-dev.yaml
  .github/workflows/build-push-prod.yaml
Labels: A0-pleasereview, B0-silent, D1-audited 👍, I8-enhancement 🎁, C1-low 📌, P7-nicetohave, Q2-easy

#110 Ipfs fixes
  bin/node/pallets/pallet-ipfs/src/functions.rs
  bin/node/pallets/pallet-ipfs/src/lib.rs
Labels: A0-pleasereview, D1-audited 👍, B7-runtimenoteworthy, B3-apinoteworthy, I2-bug 🐜, P2-asap, C7-high ❗️, I8-enhancement 🎁, Q7-involved

#111 fix: treasury tests
  frame/treasury/src/tests.rs
Labels: A0-pleasereview, D1-audited 👍, B3-apinoteworthy, P2-asap, C7-high ❗️, Q7-involved, I4-tests 🎯

#112 RPC `getStorage`
  Cargo.lock
  bin/node/pallets/pallet-ipfs/Cargo.toml
  bin/node/pallets/pallet-ipfs/rpc/Cargo.toml
  bin/node/pallets/pallet-ipfs/rpc/src/lib.rs
  bin/node/pallets/pallet-ipfs/src/functions.rs
  bin/node/pallets/pallet-ipfs/src/lib.rs
  bin/node/pallets/pallet-ipfs/src/tests.rs
Labels: A0-pleasereview, C9-critical ‼️, D1-audited 👍, B3-apinoteworthy, I8-enhancement 🎁, P5-sometimesoon, Q9-epic
