Repository CherryNetwork/Cherry-Node, pull requests merged in 2022-04, with the labels that each got.

#57 Ipfs storage fixes #37 testing `created_at` and `deleting_at` functionallity
  bin/node/pallets/pallet-ipfs/src/lib.rs
  bin/node/pallets/pallet-ipfs/src/tests.rs
Labels: D1-audited 👍, B7-runtimenoteworthy, C3-medium 📣, P5-sometimesoon, I4-tests 🎯

#58 Pallet updater genesis --- added genesis config, genesis build, genesis default, added genesis config runtime to chainspec --- runs successfully
  Cargo.lock
  bin/node/cli/src/chain_spec.rs
  bin/node/pallets/pallet-updater/Cargo.toml
  bin/node/pallets/pallet-updater/src/lib.rs
  bin/node/runtime/src/lib.rs
  bin/node/testing/src/genesis.rs
  frame/system/src/lib.rs
Labels: question, D1-audited 👍, B7-runtimenoteworthy, C3-medium 📣, A3-inprogress, Q2-easy

#56 Pallet updater voting
  Cargo.lock
  bin/node/cli/src/chain_spec.rs
  bin/node/pallets/pallet-updater/Cargo.toml
  bin/node/pallets/pallet-updater/src/lib.rs
  bin/node/runtime/src/lib.rs
  bin/node/testing/src/genesis.rs
  frame/system/src/lib.rs
Labels: A0-pleasereview, D1-audited 👍, B7-runtimenoteworthy, C7-high ❗️, I8-enhancement 🎁, Q7-involved, P5-sometimesoon

#65 fix compilation error for rustc version >= 1.60
  utils/wasm-builder/src/wasm_project.rs
Labels: A3-inprogress

#64 Fix #62 add `ensure!` to check `fee >= 1000`, a new `Error` variant and test
  bin/node/pallets/pallet-ipfs/src/lib.rs
  bin/node/pallets/pallet-ipfs/src/tests.rs
Labels: A0-pleasereview, D1-audited 👍, B7-runtimenoteworthy, C3-medium 📣, Q3-medium, I8-enhancement 🎁, P5-sometimesoon

#63 `pallet-updater` tests & benchmarks
  bin/node/pallets/pallet-ipfs/src/lib.rs
  bin/node/pallets/pallet-updater/Cargo.toml
  bin/node/pallets/pallet-updater/src/benchmarking.rs
  bin/node/pallets/pallet-updater/src/lib.rs
  bin/node/pallets/pallet-updater/src/mock.rs
  bin/node/pallets/pallet-updater/src/tests.rs
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  frame/elections-phragmen/src/lib.rs
  frame/identity/src/lib.rs
  frame/treasury/src/lib.rs
Labels: A0-pleasereview, B0-silent, D1-audited 👍, C1-low 📌

#66 Ipfs storage housekeeping
  bin/node/pallets/pallet-ipfs/src/functions.rs
  bin/node/pallets/pallet-ipfs/src/lib.rs
  bin/node/runtime/src/constants.rs
  utils/wasm-builder/src/wasm_project.rs
Labels: A0-pleasereview, D1-audited 👍, B7-runtimenoteworthy, C3-medium 📣, I8-enhancement 🎁, P5-sometimesoon

#67 Fix identity tests benchmarks --- all tests passing, all benchmarks compiling
  frame/identity/src/benchmarking.rs
  frame/identity/src/types.rs
Labels: A0-pleasereview, B0-silent, D1-audited 👍, C1-low 📌

#70 fix: pallet-ellections-phragmen benchmarks
  frame/elections-phragmen/src/benchmarking.rs
Labels: A0-pleasereview, D1-audited 👍, B7-runtimenoteworthy, C3-medium 📣, Q3-medium, P7-nicetohave

#69 fix: treasury benchmarks
  frame/treasury/src/benchmarking.rs
Labels: A0-pleasereview, D1-audited 👍, B7-runtimenoteworthy, C3-medium 📣, Q3-medium, P7-nicetohave

#71 dev
  frame/elections-phragmen/src/benchmarking.rs
  frame/identity/src/benchmarking.rs
  frame/identity/src/types.rs
  frame/treasury/src/benchmarking.rs
  utils/wasm-builder/src/wasm_project.rs
Labels: A0-pleasereview, D1-audited 👍, B3-apinoteworthy, I2-bug 🐜, P2-asap, I6-refactor 🧹, C7-high ❗️, I4-tests 🎯

#55 Pallet updater
  Cargo.lock
  Cargo.toml
  bin/node/cli/src/chain_spec.rs
  bin/node/pallets/pallet-ipfs/src/lib.rs
  bin/node/pallets/pallet-updater/Cargo.toml
  bin/node/pallets/pallet-updater/src/benchmarking.rs
  bin/node/pallets/pallet-updater/src/lib.rs
  bin/node/pallets/pallet-updater/src/mock.rs
  bin/node/pallets/pallet-updater/src/tests.rs
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  bin/node/testing/src/genesis.rs
  frame/elections-phragmen/src/lib.rs
  frame/identity/src/lib.rs
  frame/system/src/lib.rs
  frame/treasury/src/lib.rs
Labels: help wanted, A0-pleasereview, D1-audited 👍, B7-runtimenoteworthy, C3-medium 📣, Q2-easy

#72 Introduce: Updaters Membership
  Cargo.lock
  Cargo.toml
  bin/node/cli/src/chain_spec.rs
  bin/node/pallets/pallet-ipfs/src/lib.rs
  bin/node/pallets/pallet-updater/Cargo.toml
  bin/node/pallets/pallet-updater/src/benchmarking.rs
  bin/node/pallets/pallet-updater/src/lib.rs
  bin/node/pallets/pallet-updater/src/mock.rs
  bin/node/pallets/pallet-updater/src/tests.rs
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  bin/node/testing/src/genesis.rs
  frame/elections-phragmen/src/lib.rs
  frame/identity/src/lib.rs
  frame/system/src/lib.rs
  frame/treasury/src/lib.rs
Labels: A0-pleasereview, D1-audited 👍, B7-runtimenoteworthy, B3-apinoteworthy, P2-asap, C7-high ❗️, I8-enhancement 🎁, I4-tests 🎯, A8-backport

#78 Format code & hooks
  bin/node/pallets/pallet-ipfs/src/tests.rs
  bin/node/pallets/pallet-updater/src/benchmarking.rs
  bin/node/pallets/pallet-updater/src/lib.rs
  bin/node/pallets/pallet-updater/src/mock.rs
  bin/node/pallets/pallet-updater/src/tests.rs
  bin/node/runtime/src/lib.rs
  client/consensus/babe/src/verification.rs
  client/informant/src/display.rs
  client/network/src/config.rs
  client/network/src/lib.rs
  client/network/src/protocol/notifications/behaviour.rs
  client/network/src/protocol/sync/blocks.rs
  client/network/src/service/tests.rs
  client/network/src/transactions.rs
  client/peerset/src/lib.rs
  client/peerset/src/peersstate.rs
  client/service/src/builder.rs
  client/service/src/task_manager/mod.rs
  frame/assets/src/lib.rs
  frame/assets/src/tests.rs
  frame/custom/src/lib.rs
  frame/election-provider-multi-phase/src/lib.rs
  frame/elections-phragmen/src/lib.rs
  frame/support/procedural/src/pallet/parse/pallet_struct.rs
  primitives/core/src/offchain/mod.rs
  primitives/core/src/offchain/testing.rs
  primitives/io/src/lib.rs
  primitives/runtime/src/offchain/ipfs.rs
Labels: A0-pleasereview, B0-silent, D1-audited 👍, I6-refactor 🧹, P5-sometimesoon, C1-low 📌

#79 cargo fmt
  client/offchain/src/api.rs
  client/offchain/src/api/ipfs.rs
  client/offchain/src/lib.rs
Labels: A0-pleasereview, B0-silent, D1-audited 👍, I6-refactor 🧹, P5-sometimesoon, C1-low 📌

#84 Ipfs nodes housekeeping
  bin/node/pallets/pallet-ipfs/src/functions.rs
  bin/node/pallets/pallet-ipfs/src/lib.rs
  client/offchain/src/api.rs
  client/offchain/src/api/ipfs.rs
  client/offchain/src/lib.rs
Labels: A0-pleasereview, D1-audited 👍, C3-medium 📣, B3-apinoteworthy, I8-enhancement 🎁, P5-sometimesoon, Q9-epic
