Repository CherryNetwork/Cherry-Node, pull requests merged in 2022-03, with the labels that each got.

#26 fix: identities not shown properly
  frame/identity/src/lib.rs
  frame/identity/src/types.rs
Labels: bug, A0-pleasereview, D1-audited 👍, C3-medium 📣, B3-apinoteworthy

#33 add: WaitingProposals storage & logic
  bin/node/runtime/src/constants.rs
  bin/node/runtime/src/lib.rs
  frame/treasury/src/lib.rs
Labels: A0-pleasereview, D1-audited 👍, B7-runtimenoteworthy, P2-asap, C7-high ❗️, I8-enhancement 🎁

#34 feat: waiting_proposals
  bin/node/runtime/src/constants.rs
  bin/node/runtime/src/lib.rs
  frame/treasury/src/lib.rs
Labels: A0-pleasereview, D1-audited 👍, B7-runtimenoteworthy, C3-medium 📣, P2-asap, I8-enhancement 🎁

#40 remove: pallet contracts from the runtime
  bin/node/rpc/src/lib.rs
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
Labels: A0-pleasereview, D1-audited 👍, B7-runtimenoteworthy, C3-medium 📣, I6-refactor 🧹

#41 Remove `pallet_contracts` from runtime until compatibility is fixed
  bin/node/rpc/src/lib.rs
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
Labels: A0-pleasereview, D1-audited 👍, B7-runtimenoteworthy, C3-medium 📣, I6-refactor 🧹

#42 bump `spec_version` -> 270
  Cargo.lock
  bin/node/runtime/src/lib.rs
Labels: A0-pleasereview, D1-audited 👍, B7-runtimenoteworthy, C1-low 📌

#45 remove: democracy, tips & proxy
  Cargo.lock
  bin/node/cli/src/chain_spec.rs
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  bin/node/testing/src/genesis.rs
Labels: A0-pleasereview, C9-critical ‼️, D1-audited 👍, B7-runtimenoteworthy, P2-asap, I6-refactor 🧹, A6-revertrevert

#47 Runtime changes & tests
  Cargo.lock
  bin/node/cli/src/chain_spec.rs
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  bin/node/testing/src/genesis.rs
  frame/bounties/src/tests.rs
  frame/elections-phragmen/Cargo.toml
  frame/elections-phragmen/src/lib.rs
  frame/treasury/src/tests.rs
Labels: A0-pleasereview, C9-critical ‼️, D1-audited 👍, B7-runtimenoteworthy, I6-refactor 🧹, I4-tests 🎯

#48 Election Fallback
  bin/node/runtime/src/lib.rs
Labels: A0-pleasereview, C9-critical ‼️, D1-audited 👍, B7-runtimenoteworthy, I8-enhancement 🎁

#50 add: discord and telegram fields in identity.
  frame/identity/src/tests.rs
  frame/identity/src/types.rs
Labels: A0-pleasereview, D1-audited 👍, B7-runtimenoteworthy, I8-enhancement 🎁, C1-low 📌, P7-nicetohave, Q2-easy

#51 remove: gilt & uniques
  Cargo.lock
  bin/node/cli/src/chain_spec.rs
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  bin/node/testing/src/genesis.rs
Labels: A0-pleasereview, C9-critical ‼️, D1-audited 👍, B7-runtimenoteworthy, P2-asap, I6-refactor 🧹, A6-revertrevert

#52 remove: gilt & uniques
  Cargo.lock
  bin/node/cli/src/chain_spec.rs
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  bin/node/testing/src/genesis.rs
  frame/identity/src/tests.rs
  frame/identity/src/types.rs
Labels: A0-pleasereview, C9-critical ‼️, D1-audited 👍, B7-runtimenoteworthy, P2-asap, I6-refactor 🧹, A6-revertrevert
