Repository CherryNetwork/Cherry-Node, pull requests merged in 2022-05, with the labels that each got.

#87 Collective root
  bin/node/cli/src/chain_spec.rs
  bin/node/runtime/src/lib.rs
  bin/node/testing/src/genesis.rs
  frame/collective/src/lib.rs
  frame/collective/src/tests.rs
Labels: A0-pleasereview, C9-critical ‼️, D1-audited 👍, B7-runtimenoteworthy, P2-asap, I6-refactor 🧹, I8-enhancement 🎁, Q9-epic

#93 Pallet council tests fix
  Cargo.lock
  bin/node/pallets/pallet-council/Cargo.toml
  bin/node/pallets/pallet-council/src/lib.rs
  bin/node/pallets/pallet-council/src/mock.rs
  bin/node/pallets/pallet-council/src/tests.rs
Labels: A0-pleasereview, B0-silent, D1-audited 👍, P2-asap, C7-high ❗️, Q9-epic, I4-tests 🎯

#91 wip: voting "power" of council members.
  Cargo.lock
  bin/node/cli/src/chain_spec.rs
  bin/node/pallets/pallet-council/Cargo.toml
  bin/node/pallets/pallet-council/src/lib.rs
  bin/node/pallets/pallet-council/src/mock.rs
  bin/node/pallets/pallet-council/src/tests.rs
  frame/treasury/src/lib.rs
Labels: A0-pleasereview, D1-audited 👍, B3-apinoteworthy, P2-asap, I6-refactor 🧹, C7-high ❗️, I8-enhancement 🎁, Q9-epic

#94 Pallet council
  Cargo.lock
  Cargo.toml
  bin/node/cli/src/chain_spec.rs
  bin/node/pallets/pallet-council/Cargo.toml
  bin/node/pallets/pallet-council/src/benchmarking.rs
  bin/node/pallets/pallet-council/src/lib.rs
  bin/node/pallets/pallet-council/src/mock.rs
  bin/node/pallets/pallet-council/src/tests.rs
  bin/node/pallets/pallet-council/src/weights.rs
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  bin/node/testing/src/genesis.rs
  frame/treasury/src/lib.rs
Labels: A0-pleasereview, C9-critical ‼️, D1-audited 👍, B3-apinoteworthy, P2-asap, I6-refactor 🧹, I8-enhancement 🎁, Q9-epic

#95 Proposal changes
  bin/node/pallets/pallet-council/src/lib.rs
  frame/treasury/src/lib.rs
  frame/treasury/src/tests.rs
Labels: A0-pleasereview, C9-critical ‼️, D1-audited 👍, B3-apinoteworthy, I6-refactor 🧹, I8-enhancement 🎁, Q9-epic

#97 Remove pallet updater
  Cargo.lock
  Cargo.toml
  bin/node/cli/src/chain_spec.rs
  bin/node/pallets/pallet-updater/Cargo.toml
  bin/node/pallets/pallet-updater/src/benchmarking.rs
  bin/node/pallets/pallet-updater/src/lib.rs
  bin/node/pallets/pallet-updater/src/mock.rs
  bin/node/pallets/pallet-updater/src/tests.rs
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  bin/node/testing/src/genesis.rs
  frame/system/src/lib.rs
Labels: A0-pleasereview, D1-audited 👍, B7-runtimenoteworthy, Q3-medium, P2-asap, I6-refactor 🧹, C7-high ❗️
